name: iOS Appium Test

on: 
  workflow_dispatch:
  push: 

jobs:
  ios:
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install Appium-Python-Client selenium
      
      - name: Verify Python + Appium
        run: |
          python --version
          python -c "import appium; print('Appium OK')"

      # تثبيت Node + Appium
      - name: Install Appium
        run: |
          brew install node
          npm install -g appium
          appium driver install xcuitest
          # npm install -g appium@latest
          appium driver install uiautomator2
          # pip install Appium-Python-Client

      # تثبيت Python
      # - name: Install Python deps
      #   run: |
      #     pip install Appium-Python-Client
          # pip install Appium-Python-Client selenium

      - name: FULL Fix Xcode (IMPORTANT)
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          
          echo "Initializing Xcode..."
          sudo xcodebuild -runFirstLaunch || true
          
          echo "Waiting for iOS SDK..."
          for i in {1..10}; do
            xcrun --sdk iphonesimulator --show-sdk-version && break
            echo "Waiting SDK... ($i)"
            sleep 5
          done
          
          echo "Available SDK:"
          xcrun --sdk iphonesimulator --show-sdk-version

      # تشغيل Appium
      - name: Start Appium Server
        run: |
          nohup appium --port 4723 > appium.log 2>&1 &
          # nohup appium --base-path /wd/hub > appium.log 2>&1 &
          sleep 10

      # اختيار جهاز عشوائي
      # - name: Pick Simulator
      #   run: |
      #     DEVICE_ID=$(xcrun simctl list devices available | grep -m 1 "iPhone" | awk -F '[()]' '{print $2}')
      #     echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

      # - name: Pick Booted Simulator
      #   run: |
      #     DEVICE_ID=$(xcrun simctl list devices booted | grep -Eo '[A-F0-9-]{36}' | head -n 1)
      
      #     if [ -z "$DEVICE_ID" ]; then
      #       echo "❌ No booted device found, booting one..."
      
      #       DEVICE_ID=$(xcrun simctl list devices available \
      #         | grep "iPhone 16 Pro" \
      #         | grep -Eo '[A-F0-9-]{36}' | head -n 1)
      
      #       xcrun simctl boot "$DEVICE_ID"
      #       xcrun simctl bootstatus "$DEVICE_ID" -b
      #     fi
      
      #     echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
      #     echo "Using device: $DEVICE_ID"

      # - name: Set Fixed Simulator
      #   run: |
      #     DEVICE_ID="22A85A77-4D21-41B2-AA4E-BC20AFFC9E14"
      
      #     echo "Using fixed device: $DEVICE_ID"
      
      #     xcrun simctl boot "$DEVICE_ID" || true
      #     xcrun simctl bootstatus "$DEVICE_ID" -b
      
      #     echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

      # - name: Create & Boot Fixed Simulator
      #   run: |
      #     DEVICE_NAME="iPhone 16 Pro"
      #     RUNTIME="com.apple.CoreSimulator.SimRuntime.iOS-18-5"
      
      #     DEVICE_ID=$(xcrun simctl create "MyDevice" "$DEVICE_NAME" "$RUNTIME")
      
      #     xcrun simctl boot "$DEVICE_ID"
      #     xcrun simctl bootstatus "$DEVICE_ID" -b
      
      #     echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

      - name: Use Existing Simulator (Stable)
        run: |
          DEVICES=($(xcrun simctl list devices available \
            | grep -E "iPhone|iPad|Vision" \
            | grep -Eo '[A-F0-9-]{36}'))
      
          COUNT=${#DEVICES[@]}
          INDEX=$(jot -r 1 0 $((COUNT-1)))
          DEVICE_ID=${DEVICES[$INDEX]}
          # DEVICE_ID=$(xcrun simctl list devices available \
          #   | grep "iPhone 16 Pro (" \
          #   | head -n 1 \
          #   | grep -Eo '[A-F0-9-]{36}')
      
          echo "Using device: $DEVICE_ID"
      
          xcrun simctl boot "$DEVICE_ID" || true
          xcrun simctl bootstatus "$DEVICE_ID" -b
      
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV

      # - name: Pre-build WebDriverAgent (FIX 🔥)
      #   run: |
      #     echo "Building WDA manually..."
      
      #     xcodebuild \
      #       -project /Users/runner/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj \
      #       -scheme WebDriverAgentRunner \
      #       -destination "platform=iOS Simulator,id=$DEVICE_ID" \
      #       build || true

      # - name: Wait for Simulator FULL readiness (REAL FIX 🔥)
      #   run: |
      #     echo "Waiting for simulator services..."
      
      #     # فتح simulator service داخليًا
      #     xcrun simctl spawn $DEVICE_ID launchctl print system > /dev/null 2>&1 || true
      
      #     # انتظار SpringBoard (واجهة iOS)
      #     for i in {1..30}; do
      #       if xcrun simctl spawn $DEVICE_ID launchctl print system | grep -q "com.apple.springboard"; then
      #         echo "Simulator fully ready ✅"
      #         break
      #       fi
      #       echo "Waiting SpringBoard... ($i)"
      #       sleep 2
      #     done
      
      #     # انتظار إضافي بسيط (مهم جدًا)
      #     sleep 10



      - name: Kill stuck WDA (IMPORTANT 🔥)
        run: |
          killall -9 WebDriverAgentRunner || true
          killall -9 xcodebuild || true
          killall -9 iproxy || true

      # - name: Open URL
      #   run: xcrun simctl openurl $DEVICE_ID https://viscend.vercel.app

      # # انتظار تحميل الصفحة
      # - name: Wait page load
      #   run: sleep 15
      # - name: Prebuild WDA (الحل الحقيقي)
      #   run: |
      #     WDA_PATH=$(find /Users/runner/.appium -name WebDriverAgent.xcodeproj | head -n 1)
      
      #     echo "WDA PATH: $WDA_PATH"
      
      #     xcodebuild \
      #       -project "$WDA_PATH" \
      #       -scheme WebDriverAgentRunner \
      #       -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
      #       build-for-testing

      # تشغيل المحاكي
      # - name: Boot Simulator
      #   run: |
      #     xcrun simctl boot $DEVICE_ID
      #     xcrun simctl bootstatus $DEVICE_ID -b

      # - name: Get iOS Version
      #   run: |
      #     VERSION=$(xcrun --sdk iphonesimulator --show-sdk-version)
      #     echo "IOS_VERSION=$VERSION" >> $GITHUB_ENV

      # - name: Debug Xcode
      #   run: |
      #     xcodebuild -version
      #     xcrun simctl list
      #     xcrun --sdk iphonesimulator --show-sdk-version

      # تشغيل الاختبار
      - name: Run Appium Script
        run: |
          python3 test.py

      # حفظ الصور
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screen1.png
            screen2.png
