name: Qasha Maghus-Z

on: 
  workflow_dispatch:
  push: 

jobs:
  ios:
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install Appium-Python-Client selenium
      


      - name: Use Existing Simulator (Stable)
        run: |
          DEVICES=($(xcrun simctl list devices available \
            | grep -E "iPhone|iPad|Vision" \
            | grep -Eo '[A-F0-9-]{36}'))
      
          COUNT=${#DEVICES[@]}
          INDEX=$(jot -r 1 0 $((COUNT-1)))
          DEVICE_ID=${DEVICES[$INDEX]}
      
          echo "Using device: $DEVICE_ID"
      
          xcrun simctl boot "$DEVICE_ID" || true
          xcrun simctl bootstatus "$DEVICE_ID" -b
      
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV


      - name: Open URL
        run: xcrun simctl openurl $DEVICE_ID https://cryptu-compass.netlify.app

      # انتظار تحميل الصفحة
      - name: Wait page load
        run: sleep 4
        
      - name: Test random Wait load
        run: |
          SLEEP_TIME=$((8 + RANDOM % 33))  # 33 = 30 - 8 + 1
          echo "Sleeping for $SLEEP_TIME seconds..."
          sleep $SLEEP_TIME

